# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag_id: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get timestamp # get the date of the build
        id: date
        run: echo "date=$(TZ=':America/Bogota' date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo $DOCKER_TOKEN | docker login --username cdapdev2020 --password-stdin

      - name: Build images
        run: |
          docker build -t cdapdev2020/trueshield-client:${{ steps.date.outputs.date }} .
        
      - name: Push image
        run: |
          docker push cdapdev2020/trueshield-client:${{ steps.date.outputs.date }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - uses: actions/checkout@v4
    - name: Generate SSH key pair
      run: |
        ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ""
    - name: Run Terraform
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IMAGE_TAG: ${{ needs.build.outputs.tag_id }} 
      run: |
          cd terraform 
          set -e 
          terraform init -input=false
          terraform apply -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -auto-approve

          
          cd ..
          
          # Esperar 3 minutos en lo q las inatanxcias de EC2 arrancan completamente 
          sleep 180

          cd ansible
          # host guardados
          cat inventory
          export ANSIBLE_HOST_KEY_CHECKING=False
          export IMAGE_TAG=${{ needs.build.outputs.tag_id }}
          ansible-playbook -i inventory trueshield.yaml 
  
  
  